// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MyFSchool.Infrastructure.Persistence;

#nullable disable

namespace MyFSchool.Infrastructure.Migrations;

[DbContext(typeof(MyFSchoolDbContext))]
[Migration("20260722030000_AddAnnouncements")]
partial class AddAnnouncements
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        modelBuilder.Entity("MyFSchool.Domain.School.FeedPost", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<string>("AuthorDisplayName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<Guid>("AuthorUserId").HasColumnType("uniqueidentifier");
                b.Property<int>("Audience").HasColumnType("int");
                b.Property<string>("Body").IsRequired().HasMaxLength(4000).HasColumnType("nvarchar(max)");
                b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime2");
                b.Property<string>("ImageUrl").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<bool>("IsPublished").HasColumnType("bit");
                b.Property<DateTime?>("PublishedAtUtc").HasColumnType("datetime2");
                b.Property<byte[]>("RowVersion").IsRequired().IsConcurrencyToken().ValueGeneratedOnAddOrUpdate().HasColumnType("rowversion");
                b.Property<string>("Title").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<Guid?>("TargetClassId").HasColumnType("uniqueidentifier");
                b.HasKey("Id");
                b.HasIndex("IsPublished");
                b.HasIndex("CreatedAtUtc");
                b.ToTable("FeedPosts");
            });

        modelBuilder.Entity("MyFSchool.Domain.School.AnnouncementDelivery", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<int>("Channel").HasColumnType("int");
                b.Property<string>("FailureReason").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<Guid>("FeedPostId").HasColumnType("uniqueidentifier");
                b.Property<string>("RecipientDisplayName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<Guid>("RecipientUserId").HasColumnType("uniqueidentifier");
                b.Property<DateTime?>("SentAtUtc").HasColumnType("datetime2");
                b.Property<int>("Status").HasColumnType("int");
                b.HasKey("Id");
                b.HasIndex("FeedPostId", "RecipientUserId", "Channel").IsUnique();
                b.ToTable("AnnouncementDeliveries");
            });

        modelBuilder.Entity("MyFSchool.Domain.School.AnnouncementReadState", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                b.Property<Guid>("FeedPostId").HasColumnType("uniqueidentifier");
                b.Property<DateTime>("ReadAtUtc").HasColumnType("datetime2");
                b.Property<Guid>("UserId").HasColumnType("uniqueidentifier");
                b.HasKey("Id");
                b.HasIndex("FeedPostId", "UserId").IsUnique();
                b.ToTable("AnnouncementReadStates");
            });

        modelBuilder.Entity("MyFSchool.Domain.School.AnnouncementDelivery", b =>
            {
                b.HasOne("MyFSchool.Domain.School.FeedPost", "FeedPost")
                    .WithMany("Deliveries")
                    .HasForeignKey("FeedPostId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("MyFSchool.Domain.School.AnnouncementReadState", b =>
            {
                b.HasOne("MyFSchool.Domain.School.FeedPost", "FeedPost")
                    .WithMany("ReadStates")
                    .HasForeignKey("FeedPostId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("MyFSchool.Domain.School.FeedPost", b =>
            {
                b.HasOne("MyFSchool.Domain.School.ClassRoom", "TargetClass")
                    .WithMany()
                    .HasForeignKey("TargetClassId")
                    .OnDelete(DeleteBehavior.SetNull);
            });
#pragma warning restore 612, 618
    }
}
